#include <Enums_Internal.hpp>

#include <map>
#include <vector>

#include "Guid.hpp"
#include "MusicSystemMod.hpp"

const std::map<Guid, std::map<via::Language, char16_t const *>> MusicSystemMod::STRINGS_ADDED =
	{
		{L"8debd0e1-ad1f-4afc-80a7-d1013ad86e89"_guid,
		 {
			 {via::Language::Japanese, u"現実世界のBGM"},
			 {via::Language::English, u"Real World BGM"},
			 {via::Language::TransitionalChinese, u"現實世界背景音樂"},
			 {via::Language::SimplelifiedChinese, u"现实世界BGM"},
		 }},
		{L"c80c7d4e-fef6-4a17-839d-c983ceaafee8"_guid,
		 {
			 {via::Language::Japanese, u"現実世界で再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in the Real World."},
			 {via::Language::TransitionalChinese, u"設定在現實世界播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在现实世界中播放的BGM。"},
		 }},
		{L"9d3c9c45-c53f-42dd-b2fc-1beebdf63a28"_guid,
		 {
			 {via::Language::Japanese, u"ウェーブロードのBGM"},
			 {via::Language::English, u"Wave Road BGM"},
			 {via::Language::TransitionalChinese, u"電波道路背景音樂"},
			 {via::Language::SimplelifiedChinese, u"电波道路BGM"},
		 }},
		{L"8c8efb06-f15d-4844-baea-1ea64ebba80a"_guid,
		 {
			 {via::Language::Japanese, u"ウェーブロード上で再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play on Wave Roads."},
			 {via::Language::TransitionalChinese, u"設定在電波道路播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在电波道路上播放的BGM。"},
		 }},
		{L"ac468c10-eb46-4101-8dcf-922c9407a09a"_guid,
		 {
			 {via::Language::Japanese, u"電波空間のBGM"},
			 {via::Language::English, u"Wave Space BGM"},
			 {via::Language::TransitionalChinese, u"電波空間背景音樂"},
			 {via::Language::SimplelifiedChinese, u"电波空间BGM"},
		 }},
		{L"bb07dbc0-d6df-4719-b32c-ecf9f2eb7ccd"_guid,
		 {
			 {via::Language::Japanese, u"電脳空間、電波空間、番号なしのノイズウェーブで再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in Comp Spaces, EM Wave Spaces,\nCyber Cores, and non-numbered Noise Waves."},
			 {via::Language::TransitionalChinese, u"設定在電腦空間、電波空間、以及無編號雜訊電波中播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在电脑空间、电波空间、以及无编号噪声电波中播放的BGM。"},
		 }},
		{L"00214dd1-02cf-46be-9d60-7137604c6daa"_guid,
		 {
			 {via::Language::Japanese, u"ダンジョンのBGM"},
			 {via::Language::English, u"Dungeon BGM"},
			 {via::Language::TransitionalChinese, u"迷宮背景音樂"},
			 {via::Language::SimplelifiedChinese, u"迷宫BGM"},
		 }},
		{L"b91d4a7b-c8d9-46b8-ae1e-e9cb1d632015"_guid,
		 {
			 {via::Language::Japanese, u"ダンジョン、スカイウェーブ、コスモウェーブ、\n番号付きのノイズウェーブで再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in dungeons, the Sky Wave,\nthe Astro Wave, and numbered Noise Waves."},
			 {via::Language::TransitionalChinese, u"設定在迷宮、天空電波、宇宙電波、以及有編號的雜訊電波中播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在迷宫、天空电波、宇宙电波、以及带编号的噪声电波中播放的BGM。"},
		 }},
		{L"ad4fcc9e-eccf-4e64-8afb-2286132ca680"_guid,
		 {
			 {via::Language::Japanese, u"通常バトルのBGM"},
			 {via::Language::English, u"Normal Battle BGM"},
			 {via::Language::TransitionalChinese, u"一般戰鬥背景音樂"},
			 {via::Language::SimplelifiedChinese, u"普通战斗BGM"},
		 }},
		{L"13dec11f-c01f-492c-bd69-c7b0da9fb32f"_guid,
		 {
			 {via::Language::Japanese, u"通常バトルや通信対戦で再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in regular battles and online Matches."},
			 {via::Language::TransitionalChinese, u"設定在一般戰鬥與連線對戰時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在普通战斗与联机对战时播放的BGM。"},
		 }},
		{L"a95b7459-663c-4fa6-af8d-a3294250efbc"_guid,
		 {
			 {via::Language::Japanese, u"ボスバトルのBGM"},
			 {via::Language::English, u"Boss Battle BGM"},
			 {via::Language::TransitionalChinese, u"頭目戰鬥背景音樂"},
			 {via::Language::SimplelifiedChinese, u"头目战斗BGM"},
		 }},
		{L"f9548ad4-63c6-44e3-9291-a2d0000ad2b7"_guid,
		 {
			 {via::Language::Japanese, u"ボスバトルで再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in boss battles."},
			 {via::Language::TransitionalChinese, u"設定在頭目戰鬥時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在头目战斗时播放的BGM。"},
		 }},
		{L"b9144bd0-98da-439a-9da4-021c5365d153"_guid,
		 {
			 {via::Language::Japanese, u"ラストバトルのBGM"},
			 {via::Language::English, u"Last Battle BGM"},
			 {via::Language::TransitionalChinese, u"最終戰鬥背景音樂"},
			 {via::Language::SimplelifiedChinese, u"最终战斗BGM"},
		 }},
		{L"a14c26cf-289d-4c1a-a8bc-33735eb110a6"_guid,
		 {
			 {via::Language::Japanese, u"ラストバトルで再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play in the final battle."},
			 {via::Language::TransitionalChinese, u"設定在最終戰鬥時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在最终战斗时播放的BGM。"},
		 }},
		{L"6fb1bc61-3b8b-4826-a409-edc9e374f200"_guid,
		 {
			 {via::Language::Japanese, u"Winner！のBGM"},
			 {via::Language::English, u"Winner! BGM"},
			 {via::Language::TransitionalChinese, u"Winner！背景音樂"},
			 {via::Language::SimplelifiedChinese, u"Winner！BGM"},
		 }},
		{L"c89aa7f5-56ec-4dc1-b7e0-29a60836e0e7"_guid,
		 {
			 {via::Language::Japanese, u"バトル勝利時に再生するBGMを設定します。\n（報酬がないバトルの場合、一部の設定は適用されません。）"},
			 {via::Language::English, u"Select what tracks will play at the end of most won battles.\n(Some options will not apply to battles without rewards.)"},
			 {via::Language::TransitionalChinese, u"設定在戰鬥獲勝時播放的背景音樂。\n（部分選項不適用於無報酬的戰鬥。）"},
			 {via::Language::SimplelifiedChinese, u"设置在大部分战斗获胜时播放的BGM。\n（部分选项不适用于无报酬的战斗。）"},
		 }},
		{L"3744b966-9ad0-4267-bb8e-a961a0f146eb"_guid,
		 {
			 {via::Language::Japanese, u"Loser…のBGM"},
			 {via::Language::English, u"Loser... BGM"},
			 {via::Language::TransitionalChinese, u"Loser…背景音樂"},
			 {via::Language::SimplelifiedChinese, u"Loser…BGM"},
		 }},
		{L"bd4eee29-1654-46ea-b94d-1ebcec877a4f"_guid,
		 {
			 {via::Language::Japanese, u"通信対戦での敗北時に再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play at the end of lost battles in online Matches."},
			 {via::Language::TransitionalChinese, u"設定在連線對戰落敗時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在联机对战落败时播放的BGM。"},
		 }},
		{L"5e8401f5-8a28-4efb-9311-2e8fc505d79e"_guid,
		 {
			 {via::Language::Japanese, u"事件のBGM（現実世界）"},
			 {via::Language::English, u"Incident BGM (Real World)"},
			 {via::Language::TransitionalChinese, u"事件背景音樂（現實世界）"},
			 {via::Language::SimplelifiedChinese, u"出事BGM（现实世界）"},
		 }},
		{L"115ddb26-3a7a-4e90-8b60-ce581697d8ef"_guid,
		 {
			 {via::Language::Japanese, u"現実世界で事件が起きた際に再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play during incidents in the Real World."},
			 {via::Language::TransitionalChinese, u"設定在現實世界發生事件時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在现实世界发生出事时播放的BGM。"},
		 }},
		{L"6dd57050-d840-4f5c-bda4-8868441dc1aa"_guid,
		 {
			 {via::Language::Japanese, u"事件のBGM（電波世界）"},
			 {via::Language::English, u"Incident BGM (Wave World)"},
			 {via::Language::TransitionalChinese, u"事件背景音樂（電波世界）"},
			 {via::Language::SimplelifiedChinese, u"出事BGM（电波世界）"},
		 }},
		{L"9074ac1f-c5c5-4776-a97b-83066bf0b07c"_guid,
		 {
			 {via::Language::Japanese, u"電波世界で事件が起きた際に再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play during incidents in the Wave World."},
			 {via::Language::TransitionalChinese, u"設定在電波世界發生事件時播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在电波世界发生出事时播放的BGM。"},
		 }},
		{L"65c3c7c7-fa93-45fa-9cbf-f3a4cf23b862"_guid,
		 {
			 {via::Language::Japanese, u"その他のBGM"},
			 {via::Language::English, u"Miscellaneous BGM"},
			 {via::Language::TransitionalChinese, u"其他背景音樂"},
			 {via::Language::SimplelifiedChinese, u"其他BGM"},
		 }},
		{L"10428196-f3b5-452f-94f8-50e8a38139ce"_guid,
		 {
			 {via::Language::Japanese, u"その他のイベントで再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play during miscellaneous events."},
			 {via::Language::TransitionalChinese, u"設定在其他事件播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在其他事件中播放的BGM。"},
		 }},
		{L"8a38a4b9-0527-4b36-abde-c96ca132db30"_guid,
		 {
			 {via::Language::Japanese, u"タイトル画面のBGM"},
			 {via::Language::English, u"Title Screen BGM"},
			 {via::Language::TransitionalChinese, u"標題畫面背景音樂"},
			 {via::Language::SimplelifiedChinese, u"标题界面BGM"},
		 }},
		{L"69a9799a-898f-40c8-b1e0-550eb37256e7"_guid,
		 {
			 {via::Language::Japanese, u"ゲーム中のタイトル画面で再生するBGMを設定します。"},
			 {via::Language::English, u"Select what tracks will play on the in-game title screen."},
			 {via::Language::TransitionalChinese, u"設定在遊戲中標題畫面播放的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"设置在游戏内标题界面播放的BGM。"},
		 }},
		{L"3cc5ab6c-4a2a-4cb0-8816-845aefbf01ab"_guid,
		 {
			 {via::Language::Japanese, u"メインメニューのBGM"},
			 {via::Language::English, u"Main Menu BGM"},
			 {via::Language::TransitionalChinese, u"主選單背景音樂"},
			 {via::Language::SimplelifiedChinese, u"主菜单BGM"},
		 }},
		{L"bc71a2d1-54df-41b0-a2ee-670a4eb6e0a9"_guid,
		 {
			 {via::Language::Japanese, u"コレクションのメインメニューで再生するBGMを設定します。\n（待ち受けキャラクターパックがインストールされている必要があります。）"},
			 {via::Language::English, u"Select what tracks will play on the collection's Main Menu."},
			 {via::Language::TransitionalChinese, u"設定在合集主選單播放的背景音樂。\n（必須安裝主畫面待機角色組合包。）"},
			 {via::Language::SimplelifiedChinese, u"设置在合集主菜单播放的BGM。\n（必须安装待机画面角色组合包。）"},
		 }},
		{L"73c512c7-6d5d-405e-96d8-d9bcc7eff8d7"_guid,
		 {
			 {via::Language::Japanese, u"DLC BGM - Loneliness"},
			 {via::Language::English, u"DLC BGM - Loneliness"},
			 {via::Language::TransitionalChinese, u"DLC背景音樂 - Loneliness"},
			 {via::Language::SimplelifiedChinese, u"DLC BGM - Loneliness"},
		 }},
		{L"238a92fc-c37b-4319-b2e1-f40cb6915c33"_guid,
		 {
			 {via::Language::Japanese, u"ゲーム中で「Loneliness - Summer Shade Version」を再生するか設定します。\n（上記の設定よりも優先されます。）"},
			 {via::Language::English, u"Select whether to play Loneliness - Summer Shade Version in-game.\n(This takes priority over the above settings.)"},
			 {via::Language::TransitionalChinese, u"設定是否在遊戲中播放「Loneliness - Summer Shade Version」。\n（此項目的優先度高於上述設定。）"},
			 {via::Language::SimplelifiedChinese, u"设置是否在游戏内播放“Loneliness - Summer Shade Version”。\n（此项优先于上述设置生效。）"},
		 }},
		{L"28a49ef5-fc0c-48c5-a8eb-60c92ba20cc8"_guid,
		 {
			 {via::Language::Japanese, u"DLC BGM - コスモウェーブ"},
			 {via::Language::English, u"DLC BGM - Astro Wave"},
			 {via::Language::TransitionalChinese, u"DLC背景音樂 - 宇宙電波"},
			 {via::Language::SimplelifiedChinese, u"DLC BGM - 宇宙电波"},
		 }},
		{L"5491219b-1b6e-4e37-a894-e065e37d7bb2"_guid,
		 {
			 {via::Language::Japanese, u"ゲーム中で「コスモウェーブ - Brilliant Expanse Version」を再生するか設定します。\n（上記の設定よりも優先されます。）"},
			 {via::Language::English, u"Select whether to play Astro Wave - Brilliant Expanse Version in-game.\n(This takes priority over the above settings.)"},
			 {via::Language::TransitionalChinese, u"設定是否在遊戲中播放「宇宙電波 - Brilliant Expanse Version」。\n（此項目的優先度高於上述設定。）"},
			 {via::Language::SimplelifiedChinese, u"设置是否在游戏内播放“宇宙电波 - Brilliant Expanse Version”。\n（此项优先于上述设置生效。）"},
		 }},
		{L"cc097b76-9d12-40db-91ee-dff3e0852892"_guid,
		 {
			 {via::Language::Japanese, u"DLC BGM - 孤高の旋律"},
			 {via::Language::English, u"DLC BGM - Anthem of the Solitary"},
			 {via::Language::TransitionalChinese, u"DLC背景音樂 - 孤高的旋律"},
			 {via::Language::SimplelifiedChinese, u"DLC BGM - 孤高的旋律"},
		 }},
		{L"8313007b-6258-4f73-82e3-07952e8d9831"_guid,
		 {
			 {via::Language::Japanese, u"ゲーム中で「孤高の旋律 - Howling Void Version」を再生するか設定します。\n（上記の設定よりも優先されます。）"},
			 {via::Language::English, u"Select whether to play Anthem of the Solitary - Howling Void Version in-game.\n(This takes priority over the above settings.)"},
			 {via::Language::TransitionalChinese, u"設定是否在遊戲中播放「孤高的旋律 - Howling Void Version」。\n（此項目的優先度高於上述設定。）"},
			 {via::Language::SimplelifiedChinese, u"设置是否在游戏内播放“孤高的旋律 - Howling Void Version”。\n（此项优先于上述设置生效。）"},
		 }},
		{L"31d45ae4-128e-4172-820f-4fd2b06510a5"_guid,
		 {
			 {via::Language::Japanese, u"DLC BGM - 明るい室内"},
			 {via::Language::English, u"DLC BGM - Cheerful Indoors"},
			 {via::Language::TransitionalChinese, u"DLC背景音樂 - 明亮的室內"},
			 {via::Language::SimplelifiedChinese, u"DLC BGM - 明亮的室内"},
		 }},
		{L"61511466-dd94-4c00-ae88-4a8878002c8b"_guid,
		 {
			 {via::Language::Japanese, u"ゲーム中で「明るい室内 - School Days Version」を再生するか設定します。\n（上記の設定よりも優先されます。）"},
			 {via::Language::English, u"Select whether to play Cheerful Indoors - School Days Version in-game.\n(This takes priority over the above settings.)"},
			 {via::Language::TransitionalChinese, u"設定是否在遊戲中播放「明亮的室內 - School Days Version」。\n（此項目的優先度高於上述設定。）"},
			 {via::Language::SimplelifiedChinese, u"设置是否在游戏内播放“明亮的室内 - School Days Version”。\n（此项优先于上述设置生效。）"},
		 }},
		{L"c564c411-216f-498f-9c53-459408c675d5"_guid,
		 {
			 {via::Language::Japanese, u"変更なし"},
			 {via::Language::English, u"No Change"},
			 {via::Language::TransitionalChinese, u"不變更"},
			 {via::Language::SimplelifiedChinese, u"不更改"},
		 }},
		{L"efab3c28-9b48-442f-9fcb-7cf75b46b7bc"_guid,
		 {
			 {via::Language::Japanese, u"「BGM選択」の設定に従って通常のBGMを再生します。"},
			 {via::Language::English, u"Play the normal track as determined by BGM Selection."},
			 {via::Language::TransitionalChinese, u"依照「選擇背景音樂」的設定播放一般背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"按照“选择BGM”的设置播放普通BGM。"},
		 }},
		{L"33fffdce-f115-4cd5-ade2-2a168f47d19a"_guid,
		 {
			 {via::Language::Japanese, u"BGM OFF"},
			 {via::Language::English, u"Music Off"},
			 {via::Language::TransitionalChinese, u"關閉背景音樂"},
			 {via::Language::SimplelifiedChinese, u"关闭BGM"},
		 }},
		{L"7f561d13-08c8-43c5-af02-4248afa489e4"_guid,
		 {
			 {via::Language::Japanese, u"この種類のBGMは再生されません。"},
			 {via::Language::English, u"Background music is disabled for this type of track."},
			 {via::Language::TransitionalChinese, u"停用此類型曲目的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"禁用此类型曲目的BGM。"},
		 }},
		{L"b46d7983-3acf-40a4-8c71-3f2bfb7d7b89"_guid,
		 {
			 {via::Language::Japanese, u"常にオリジナル"},
			 {via::Language::English, u"Always Original"},
			 {via::Language::TransitionalChinese, u"總是播放原版"},
			 {via::Language::SimplelifiedChinese, u"总是播放原版"},
		 }},
		{L"bf4b7003-90ae-45fa-bcda-66d72fa818e5"_guid,
		 {
			 {via::Language::Japanese, u"常にオリジナル版のBGMを再生します。"},
			 {via::Language::English, u"Always play the original version of the track."},
			 {via::Language::TransitionalChinese, u"總是播放原版的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"总是播放原版BGM。"},
		 }},
		{L"773ac3ba-06fc-489c-85f1-589efb6b546f"_guid,
		 {
			 {via::Language::Japanese, u"常にアレンジ"},
			 {via::Language::English, u"Always Arranged"},
			 {via::Language::TransitionalChinese, u"總是播放編曲版"},
			 {via::Language::SimplelifiedChinese, u"总是播放改编版"},
		 }},
		{L"7fd7bc1a-88ee-4631-bbec-a731d86deed5"_guid,
		 {
			 {via::Language::Japanese, u"常にアレンジ版のBGMを再生します。"},
			 {via::Language::English, u"Always play the arranged version of the track."},
			 {via::Language::TransitionalChinese, u"總是播放編曲版的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"总是播放改编版BGM。"},
		 }},
		{L"c12ba05a-7bbc-4e46-b510-53a361c262f4"_guid,
		 {
			 {via::Language::Japanese, u"優先モード <ICON LAUNCHER_DECIDE>"},
			 {via::Language::English, u"Preferred Mix <ICON LAUNCHER_DECIDE>"},
			 {via::Language::TransitionalChinese, u"偏好模式 <ICON LAUNCHER_DECIDE>"},
			 {via::Language::SimplelifiedChinese, u"首选模式 <ICON LAUNCHER_DECIDE>"},
		 }},
		{L"501e2a85-77ba-4f87-a7a1-b672e5674e54"_guid,
		 {
			 {via::Language::Japanese, u"フェイバリット登録されている場合、常にオリジナル版かアレンジ版のBGMを再生します。\n（全BGM共通のリストです。）"},
			 {via::Language::English, u"Always play the original or arranged track if that version is marked as Favorite.\n(This list is shared for all track types.)"},
			 {via::Language::TransitionalChinese, u"若有登錄至我的最愛，則總是優先播放原版或編曲版的背景音樂。\n（此清單為所有曲目類型共用。）"},
			 {via::Language::SimplelifiedChinese, u"若已添加至收藏，将总是优先播放原版或改编版的BGM。\n（此列表对所有类型曲目通用。）"},
		 }},
		{L"36fac9cf-514b-45f7-b015-b5b54b4817c3"_guid,
		 {
			 {via::Language::Japanese, u"プレイリスト <ICON LAUNCHER_DECIDE>"},
			 {via::Language::English, u"Playlist <ICON LAUNCHER_DECIDE>"},
			 {via::Language::TransitionalChinese, u"播放清單 <ICON LAUNCHER_DECIDE>"},
			 {via::Language::SimplelifiedChinese, u"播放列表 <ICON LAUNCHER_DECIDE>"},
		 }},
		{L"297584f6-5da9-4131-99fd-365f2d8746ac"_guid,
		 {
			 {via::Language::Japanese, u"この種類のBGM専用のフェイバリットリストから、\nランダムに選ばれた曲を常に再生します。"},
			 {via::Language::English, u"Always play tracks randomly selected from a\ndedicated list of Favorites for this type of track."},
			 {via::Language::TransitionalChinese, u"總是從此類型曲目專屬的我的最愛清單中，隨機挑選樂曲播放。"},
			 {via::Language::SimplelifiedChinese, u"总是从该类型曲目专属的收藏列表中，随机挑选曲目播放。"},
		 }},
		{L"c5451ab5-0f50-45c0-8368-de71c13aa44b"_guid,
		 {
			 {via::Language::Japanese, u"フェイバリット <ICON LAUNCHER_DECIDE>"},
			 {via::Language::English, u"Favorites <ICON LAUNCHER_DECIDE>"},
			 {via::Language::TransitionalChinese, u"我的最愛 <ICON LAUNCHER_DECIDE>"},
			 {via::Language::SimplelifiedChinese, u"收藏 <ICON LAUNCHER_DECIDE>"},
		 }},
		{L"99b3bbca-167c-416c-aa9d-1349dac7b784"_guid,
		 {
			 {via::Language::Japanese, u"通常のフェイバリットリストからランダムに選ばれた曲を常に再生します。"},
			 {via::Language::English, u"Always play tracks randomly selected from your regular list of Favorites."},
			 {via::Language::TransitionalChinese, u"總是從一般的我的最愛清單中，隨機挑選樂曲播放。"},
			 {via::Language::SimplelifiedChinese, u"总是从常规收藏列表中，随机挑选曲目播放。"},
		 }},
		{L"0c174efc-4ff0-42ea-98d2-c0956ca6c5ba"_guid,
		 {
			 {via::Language::Japanese, u"フィールド"},
			 {via::Language::English, u"Field"},
			 {via::Language::TransitionalChinese, u"場地"},
			 {via::Language::SimplelifiedChinese, u"自由移动"},
		 }},
		{L"53ff37ca-a276-470c-b310-8c0ad3ce1349"_guid,
		 {
			 {via::Language::Japanese, u"フィールド画面のBGMを途切れることなく再生します。\n（通信対戦には適用されません。）"},
			 {via::Language::English, u"Play the background music from the Field Screen uninterrupted.\n(Does not apply to online Matches.)"},
			 {via::Language::TransitionalChinese, u"不中斷地繼續播放場地畫面的背景音樂。\n（不適用於連線對戰。）"},
			 {via::Language::SimplelifiedChinese, u"不中断地继续播放自由移动界面的BGM。\n（不适用于联机对战。）"},
		 }},
		{L"c7e77ba9-a882-4d37-a11b-e5900d140d51"_guid,
		 {
			 {via::Language::Japanese, u"フィールドオリジナル"},
			 {via::Language::English, u"Field Original"},
			 {via::Language::TransitionalChinese, u"場地原版"},
			 {via::Language::SimplelifiedChinese, u"自由移动原版"},
		 }},
		{L"18b51d97-8636-4bb6-b6b7-4e5a2c46afd5"_guid,
		 {
			 {via::Language::Japanese, u"フィールド画面のオリジナル版BGMを途切れることなく再生します。\n（通信対戦には適用されません。）"},
			 {via::Language::English, u"Play the original version of the background music from the Field Screen uninterrupted.\n(Does not apply to online Matches.)"},
			 {via::Language::TransitionalChinese, u"不中斷地繼續播放場地畫面的原版背景音樂。\n（不適用於連線對戰。）"},
			 {via::Language::SimplelifiedChinese, u"不中断地继续播放自由移动界面的原版BGM。\n（不适用于联机对战。）"},
		 }},
		{L"91937c25-8452-45d8-a735-aa569695badb"_guid,
		 {
			 {via::Language::Japanese, u"フィールドアレンジ"},
			 {via::Language::English, u"Field Arranged"},
			 {via::Language::TransitionalChinese, u"場地編曲版"},
			 {via::Language::SimplelifiedChinese, u"自由移动改编版"},
		 }},
		{L"bdbd21a1-9136-4639-bf6a-bda1fdc18e64"_guid,
		 {
			 {via::Language::Japanese, u"フィールド画面のアレンジ版BGMを途切れることなく再生します。\n（通信対戦には適用されません。）"},
			 {via::Language::English, u"Play the arranged version of the background music from the Field Screen uninterrupted.\n(Does not apply to online Matches.)"},
			 {via::Language::TransitionalChinese, u"不中斷地繼續播放場地畫面的編曲版背景音樂。\n（不適用於連線對戰。）"},
			 {via::Language::SimplelifiedChinese, u"不中断地继续播放自由移动界面的改编版BGM。\n（不适用于联机对战。）"},
		 }},
		{L"0a1089a5-f79f-45d4-9329-f159d2d4fdc2"_guid,
		 {
			 {via::Language::Japanese, u"バトル"},
			 {via::Language::English, u"Battle"},
			 {via::Language::TransitionalChinese, u"戰鬥"},
			 {via::Language::SimplelifiedChinese, u"战斗"},
		 }},
		{L"22089bb3-1ed9-498f-bb7b-b10063cdc380"_guid,
		 {
			 {via::Language::Japanese, u"バトル画面のBGMを途切れることなく再生します。"},
			 {via::Language::English, u"Play the background music from the Battle Screen uninterrupted."},
			 {via::Language::TransitionalChinese, u"不中斷地繼續播放戰鬥畫面的背景音樂。"},
			 {via::Language::SimplelifiedChinese, u"不中断地继续播放战斗界面的BGM。"},
		 }},
		{L"079c9622-16d9-4871-b199-c25eb73196c8"_guid,
		 {
			 {via::Language::Japanese, u"<ICON LAUNCHER_DECIDE> リスト編集"},
			 {via::Language::English, u"<ICON LAUNCHER_DECIDE> Edit List"},
			 {via::Language::TransitionalChinese, u"<ICON LAUNCHER_DECIDE> 編輯清單"},
			 {via::Language::SimplelifiedChinese, u"<ICON LAUNCHER_DECIDE> 编辑列表"},
		 }},
};

const std::map<std::string_view, std::map<via::Language, char16_t const *>> MusicSystemMod::STRINGS_REPLACED =
	{
		{"Common_MsgGUI00030000_Sound_16",
		 {
			 {via::Language::Japanese, u"フェイバリット <ICON LAUNCHER_DECIDE>"},
			 {via::Language::English, u"Favorites <ICON LAUNCHER_DECIDE>"},
			 {via::Language::TransitionalChinese, u"我的最愛 <ICON LAUNCHER_DECIDE>"},
			 {via::Language::SimplelifiedChinese, u"收藏 <ICON LAUNCHER_DECIDE>"},
		 }},
		{"Common_MsgGUI00030000_Sound_Guid_5",
		 {
			 {via::Language::Japanese, u"ゲーム中で再生するBGMのデフォルト設定を変更します。\n（各BGMの種類ごとに下部で個別設定も可能です。）"},
			 {via::Language::English, u"Set the default setting for what tracks will play in-game.\n(Individual track types can be adjusted below.)"},
			 {via::Language::TransitionalChinese, u"設定在遊戲中播放背景音樂的預設設定。\n（可在下方針對各個曲目類型進行個別調整。）"},
			 {via::Language::SimplelifiedChinese, u"设置在游戏内播放BGM的默认设置。\n（可在下方对各类型的曲目进行单独调整。）"},
		 }},
};